#!/usr/bin/perl
use strict;
my $PROJECT_ROOT = "$ENV{'HOME'}/wa/github/resume-tex/";
my $SUFFIX = 'tex';
my $result = 0;
chomp(my $prepath = $ENV{'PWD'});

# check the input arguement
if (@ARGV == 1)
{
  chomp(my $fullpath = @ARGV[0]);

  # test the suffix of file, which should be 'tex'
  if ((my $tmp = (split (/\./, $fullpath))[-1]) eq $SUFFIX)
  {
    my $target = (split (/\//, $fullpath))[-1];
    $target = (split (/\./, $target))[0];
    # set absolute path of the input file
    $fullpath = $prepath . "/" . $fullpath;
    print "PY---> full path:\t$fullpath\nPY---> target:\t\t$target\n";

    # test the current directory, change it to PROJECT_HOME
    if ($prepath ne $PROJECT_ROOT)
    {
      chdir "$PROJECT_ROOT" or die "cannot chdir to $PROJECT_ROOT: $!";
    }

    # excute the shell command
    $result = system "latex -output-directory=./tmp/ $fullpath; dvipdf ./tmp/$target.dvi ./tmp/$target.pdf; mv ./tmp/$target.pdf ./pdf_repo/;";
    $result ? print "PY---> shell command failed!\n" : print "PY---> success!\n";
  }
  else
  {
    $result = 1;
    print "PY---> please give a tex file as input. \n";
  }
}
else
{
  $result = 1;
  print "PY---> argument error. please make sure only one argument is provided. \n";
}

if ($result)
{
# when error display usage instruction
print ("=== Usage ===
./createpdf /path/to/my.tex
");
}
